### ISSUE TITLE
Missing files when evaluating zh_medcase

### ISSUE THREAD

**Issue by Gjw2333** [JOHNNY-fans/MedOdyssey#2]
Thank you for your contributing work!
However, when I evaluated the output in zh_medcase, the required answer_correct.json was not included in the project. Will there be an opportunity to provide this file later? Or please tell me where the file came from and how to handle it. 
Thanks again.

**Comment by JOHNNY-fans** [comment]
Thank you for your interest in our work and apologies for the missing files. We have uploaded the data and you can view it at [answer_correct.json](https://github.com/JOHNNY-fans/MedOdyssey/blob/main/dataset/raw_data/zh_medcase/answer_correct.json)

**Comment by JOHNNY-fans** [comment]
> Thank you for your contributing work! However, when I evaluated the output in zh_medcase, the required answer_correct.json was not included in the project. Will there be an opportunity to provide this file later? Or please tell me where the file came from and how to handle it. Thanks again.

Thank you for your interest in our work and apologies for the missing files. We have uploaded the data and you can view it at [answer_correct.json](https://github.com/JOHNNY-fans/MedOdyssey/blob/main/dataset/raw_data/zh_medcase/answer_correct.json)

**Comment by Gjw2333** [comment]
> > Thank you for your contributing work! However, when I evaluated the output in zh_medcase, the required answer_correct.json was not included in the project. Will there be an opportunity to provide this file later? Or please tell me where the file came from and how to handle it. Thanks again.
> 
> Thank you for your interest in our work and apologies for the missing files. We have uploaded the data and you can view it at [answer_correct.json](https://github.com/JOHNNY-fans/MedOdyssey/blob/main/dataset/raw_data/zh_medcase/answer_correct.json)

Much appreciate! It really helped me out.
